version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  test:
    working_directory: ~/repo
    parameters:
      tag:
        type: string
    executor:
      name: node/default
      tag: << parameters.tag >>
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Run tests
                command: |
                  mkdir -p ~/reports/ava
                  npm run test -- --tap | npx tap-xunit > ~/reports/ava/results.xml
            - store_test_results:
                path: ~/reports
            - store_artifacts:
                path: ~/reports
            - persist_to_workspace:
                root: ~/repo
                paths: .

  publish:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: latest
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  parameter-test:
    jobs:
      - test:
          tag: "8.16"
      - test:
          tag: "10.16"
      - test:
          tag: "12.6"
  test-publish:
    jobs:
      - test:
          tag: latest
          filters:
            tags:
              only: /^v.*/
          branches:
            ignore: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
          branches:
            ignore: /.*/
