version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys: v1-dependencies-

      - run: yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p ~/reports
            npm run test -- --tap | npx tap-xunit > ~/reports/ava.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master